- url: "http://rj.bomnegocio.com/rio-de-janeiro-e-regiao/centro/videogames?ot=1&q=3DS"
  provider: "bomnegocio"
  title: "Nintendo 3DS no Centro do Rio de Janeiro"
- url: "http://rj.bomnegocio.com/rio-de-janeiro-e-regiao/zona-sul/videogames?ot=1&q=3DS"
  provider: "bomnegocio"
  title: "Nintendo 3DS na Zona Sul do Rio de Janeiro"
- url: "http://cidaderiodejaneiro.olx.com.br/nf/video-games-consoles-cat-802/3ds-zona_centro~76"
  provider: "olx"
  title: "Nintendo 3DS no Centro do Rio de Janeiro"
- url: "http://cidaderiodejaneiro.olx.com.br/nf/ddd-21-47-video-games-consoles-cat-802/3ds-zona_sul~74"
  provider: "olx"
  title: "Nintendo 3DS na Zona Sul do Rio de Janeiro"
- url: "http://games.mercadolivre.com.br/nintendo-3ds-jogos/mario-kart-7_PriceRange_0-80"
  provider: "mercadolivre"
  title: "Mario Kart 7 - Nintendo 3DS"
- url: "http://games.mercadolivre.com.br/nintendo-3ds-jogos/super-smash-bros_PriceRange_0-100"
  provider: "mercadolivre"
  title: "Super Smash Bros - Nintendo 3DS"
