- url: "http://rj.bomnegocio.com/rio-de-janeiro-e-regiao/centro/videogames?ot=1&q=Nintendo+3DS"
  provider: "bomnegocio"
  title: "Nintendo 3DS no Centro do Rio de Janeiro"
- url: "http://rj.bomnegocio.com/rio-de-janeiro-e-regiao/zona-sul/videogames?ot=1&q=Nintendo+3DS"
  provider: "bomnegocio"
  title: "Nintendo 3DS na Zona Sul do Rio de Janeiro"
- url: "http://cidaderiodejaneiro.olx.com.br/nf/video-games-consoles-cat-802/nintendo%2B3ds-zona_centro~76"
  provider: "olx"
  title: "Nintendo 3DS no Centro do Rio de Janeiro"
- url: "http://cidaderiodejaneiro.olx.com.br/nf/ddd-21-47-video-games-consoles-cat-802/nintendo%2B3ds-zona_sul~74"
  provider: "olx"
  title: "Nintendo 3DS na Zona Sul do Rio de Janeiro"
