bomnegocio:
  title: "Bom Negocio"
  ad_node_xpath: "//div[contains(@class,'search_listing_adsBN_section')]/ul/li[contains(@class,'list_adsBN_item')]/div/a[contains(@class,'whole_area_link')]"
  ad_id_xpath: "@name"
  ad_title_xpath: "@title"
  ad_url_pattern: "http://bomnegocio.com/vi/%{id}.html"
olx:
  title: "OLX"
  ad_node_xpath: "//div[@id='itemListContent']/div[contains(@class,'the-list')]/div[contains(@class,'item')]"
  ad_id_xpath: "@data-item-id"
  ad_title_xpath: "a/@title"
  ad_url_pattern: "http://www.olx.com.br/iid-%{id}"
mercadolivre:
  title: "Mercado Livre"
  ad_node_xpath: "//ol[@id='searchResults']/li[contains(@class,'article')]/div[contains(@class,'rowItem')]"
  ad_id_xpath: "number(substring-after(@id,'MLB'))"
  ad_title_xpath: "string(h2[contains(@class,'list-view-item-title')]/a)"
  ad_url_pattern: "http://produto.mercadolivre.com.br/MLB-%{id}-_JM"
